- name: Create AWS Stack for the backend
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    keypair: id_rsa
    instance_type: t3.large
    j_instance_type: t3.medium
    db_instance_type: db.t2.micro
    image: ami-0bdf93799014acdc4
    region: eu-central-1
    vpcdefault_id: vpc-c7c8c8ae
    db_user: root
    db_pass: 
  tasks:
    - name: Gather facts about VPCs
      ec2_vpc_net_facts:
        region: "{{ region }}" 
      register: vpcs

    - name: SSH from outside Security Group
      ec2_group:
       region: "{{ region }}"
       name: ec2_ssh_cp
       description: SSH from outside
       vpc_id: "{{ vpcdefault_id }}"
       rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      register: ssh_security_group  

    - name: Access web server Security Group
      ec2_group:
       region: "{{ region }}"
       name: ec2_web_cp
       description: Access web server on ports 80 and 8080
       vpc_id: "{{ vpcdefault_id }}"
       rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      register: web_security_group  

    - name: Access RDS from EC2 Security Group
      ec2_group:
       region: "{{ region }}"
       name: ec2_rds_cp
       description: Access RDS from EC2
       vpc_id: "{{ vpcdefault_id }}"
       rules:
        - proto: tcp
          from_port: 3306
          to_port: 3306
          group_name: "{{ web_security_group.group_name }}"
      register: rds_security_group          
      
    - name: Launch Webapp EC2 Instance
      ec2:   
          key_name: "{{ keypair }}"
          group: ['default','ec2_ssh_cp', 'ec2_web_cp']
          instance_type: "{{ instance_type }}"
          image: "{{ image }}"
          wait: true
          region: "{{ region }}"
          volumes:
            - device_name: /dev/sda1
              volume_type: gp2
              volume_size: 20
              delete_on_termination: true
      register: ec2
      
   - name: Launch Jenkins EC2 Instance
      ec2:   
          key_name: "{{ keypair }}"
          group: ['default','ec2_ssh_cp', 'ec2_web_cp']
          instance_type: "{{ j_instance_type }}"
          image: "{{ image }}"
          wait: true
          region: "{{ region }}"
          volumes:
            - device_name: /dev/sda1
              volume_type: gp2
              volume_size: 20
              delete_on_termination: true
      register: j_ec2    
      
    - name: Create RDS MySQL Instance
      rds:
          command: create
          region: "{{ region }}"
          instance_name: cpdb
          db_engine: MySQL
          size: 10
          instance_type: "{{ db_instance_type }}"
          vpc_security_groups: "{{ rds_security_group.group_id }}"
          username: "{{ db_user }}"
          password: "{{ db_pass }}"
      
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"
      
    - name: Print all webapp variables
      debug: var=ec2
      
    - name: Print all webapp variables
      debug: var=j_ec2
